### ISSUE TITLE
Make compatible PHP 8.1 & 8.2

### ISSUE THREAD

**Issue by Luifer-dnk** [Kaudaj/kjblocks#1]
Thank you very much for this practical module.

Will it be compatible soon with versions of PHP (php8.1 php8.2)?

Thanks again.

**Comment by Luifer-dnk** [comment]
Error !!!

Working !!!

**Comment by tom-combet** [comment]
Yep, it should work now with [1.1.0 release](https://github.com/Kaudaj/kjblocks/releases/tag/v1.1.0)! 😃
